project:
  type: website
  preview:
    browser: true
    
website:
  title: "SARA Institute of Data Science"
  description: "The best data science education is free and open-source. SARA is committed to provide free data science education to under-represented communities in India."
  image: logo-sara.png
  favicon: images/logo-sara.png
  twitter-card: true
  site-url: https://sara-course-r4b.netlify.app
  

  navbar:
    logo: images/logo-sara.png
    
    right:
      - icon: github
        href: https://github.com/sara-institute
      - text: "{{< iconify fa6-brands bluesky >}}"
        href: https://bsky.app/profile/sarainstitute.bsky.social
      - icon: linkedin
        href: "https://www.linkedin.com/company/104133989/admin/dashboard/"
      - icon: youtube
        href: "https://www.youtube.com/@SARADataScience"

format:
  html:
    theme: cosmo     